-- ═══════════════════════════════════════════════════════════════
-- Studio Favola — Esquema do banco (Supabase / PostgreSQL)
--
-- ATENÇÃO: as definições de tabela abaixo foram INFERIDAS a partir
-- do código do app (index.html) — os tipos e constraints reais podem
-- diferir. Elas servem como documentação e para recriar o banco do
-- zero. NÃO execute os CREATE TABLE em um banco que já tem dados.
--
-- A seção "MIGRAÇÃO OBRIGATÓRIA" no final DEVE ser executada no
-- SQL Editor do Supabase antes de publicar a versão revisada do app
-- (commit "Segurança: aprovação de ajuste por user.id...").
-- ═══════════════════════════════════════════════════════════════

-- ── usuarios ─────────────────────────────────────────────────────
-- Espelha auth.users; guarda o nome de exibição da sócia.
create table if not exists usuarios (
  id   uuid primary key references auth.users(id),
  nome text
);

-- ── contratos (página Projetos) ──────────────────────────────────
create table if not exists contratos (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz default now(),
  numero           integer,
  nome_contrato    text,
  cliente          text,
  contato          text,
  tipologia        text,        -- Interiores | Arquitetônico | Comercial | Arq + Int
  servico          text,        -- Projeto | Consultoria | Detalhamento | Acompanhamento
  valor_contrato   numeric,
  parcelas         integer default 1,
  a_receber        numeric default 0,
  conta            text,        -- 'pessoal' (PF) | 'jurídica' (PJ)
  status           text,        -- Ativo | Proposta | Pausado | Finalizado | Descontinuado
  data_inicio      date,
  data_fim         date,
  cidade           text,
  uf               text,
  origem           text,        -- Indicação | Family & friends | Contato comercial
  metros_quadrados text,
  obs              text
);

-- ── entradas (Financeiro) ────────────────────────────────────────
create table if not exists entradas (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz default now(),
  contrato_id    bigint references contratos(id),
  nome_contrato  text,
  cliente        text,
  tipo_entrada   text,          -- 'projeto' | 'rt' | 'ajuste de caixa'
  valor          numeric,
  data_pagamento date,
  conta          text,          -- 'pessoal' | 'jurídica'
  forma_pagto    text,          -- PIX | TED | Boleto | Cartão | Ajuste
  status         text,          -- Pago | A Receber | Atrasado
  -- DÍVIDA CONHECIDA: mes_ano é texto em formato legado 'DD/MM/YYYY'
  -- (sempre dia 01). O app normaliza vários formatos em normalizaMesAno().
  -- Não migrar sem plano — há dados de produção em formatos mistos.
  mes_ano        text,
  obs            text
);

-- ── saidas (Financeiro / Sócias) ─────────────────────────────────
create table if not exists saidas (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz default now(),
  contrato_id    bigint references contratos(id),
  nome_contrato  text,
  tipo_saida     text,          -- retirada de lucros | pró-labore | projeto despesa |
                                -- escritório despesa | marketing | honorários | imposto |
                                -- ajuste de caixa | outro
  descricao      text,
  valor          numeric,
  data_pagamento date,
  conta          text,
  socia          text,          -- Fernanda | Laís | Ambas | null
  status         text,          -- Pago | A Pagar | Atrasado
  mes_ano        text,          -- mesmo formato legado de entradas.mes_ano
  obs            text
);

-- ── rt_comissoes (página RT / Comissões) ─────────────────────────
create table if not exists rt_comissoes (
  id                 bigint generated by default as identity primary key,
  created_at         timestamptz default now(),
  projeto            text,      -- nome_contrato do contrato relacionado
  categoria          text,      -- Marcenaria, Pedras, Iluminação, ...
  fornecedor         text,
  contato_fornecedor text,
  valor_venda        numeric,
  percentual_rt      numeric,   -- fração (0.10 = 10%)
  valor_rt           numeric,
  a_receber          numeric default 0,
  data_fechamento    date,
  conta              text,
  status             text       -- A receber | Pago | Inadimplência
);

-- ── fluxo_caixa (histórico mensal; hoje o app calcula em memória) ─
create table if not exists fluxo_caixa (
  id      bigint generated by default as identity primary key,
  mes_ano text
  -- demais colunas não utilizadas pelo app atual
);

-- ── contas_bancarias (aba Contas do Financeiro) ──────────────────
create table if not exists contas_bancarias (
  id            bigint generated by default as identity primary key,
  nome          text,           -- Ex: Nubank PJ, C6 PF
  tipo          text,           -- Conta Corrente PJ | Conta Corrente PF | Poupança | Carteira | Outro
  saldo_atual   numeric default 0,
  atualizado_em date,
  obs           text
);

-- ── ajustes_caixa (conciliação com dupla aprovação) ──────────────
create table if not exists ajustes_caixa (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz default now(),
  updated_at        timestamptz,
  valor_novo        numeric,
  valor_anterior    numeric,
  diferenca         numeric,
  motivo            text,
  data_referencia   date,
  solicitado_por    text,       -- nome de exibição (legado)
  aprovado_por      text,       -- nome de exibição (legado)
  solicitado_por_id uuid,       -- auth.users.id — ver migração abaixo
  aprovado_por_id   uuid,       -- auth.users.id — ver migração abaixo
  status            text        -- pendente | aprovado | rejeitado
);

-- ═══════════════════════════════════════════════════════════════
-- RLS — Row Level Security
--
-- Verificado em 04/07/2026 via REST anônimo: SELECT retorna vazio e
-- INSERT é rejeitado com 42501, ou seja, o RLS JÁ ESTÁ ATIVO e
-- bloqueando acesso sem login. As políticas abaixo documentam o
-- padrão esperado (acesso total apenas a usuários autenticados);
-- use-as como referência ou para recriar o projeto.
-- ═══════════════════════════════════════════════════════════════
-- Exemplo por tabela (repita para cada uma):
--
--   alter table contratos enable row level security;
--   create policy "authenticated full access" on contratos
--     for all to authenticated using (true) with check (true);

-- ═══════════════════════════════════════════════════════════════
-- MIGRAÇÃO OBRIGATÓRIA — executar ANTES de publicar a versão revisada
-- ═══════════════════════════════════════════════════════════════

alter table ajustes_caixa add column if not exists solicitado_por_id uuid;
alter table ajustes_caixa add column if not exists aprovado_por_id   uuid;

-- Reforço no banco: impede que a mesma pessoa solicite e aprove
-- (a validação no app pode ser burlada pelo console do navegador;
--  este trigger garante a regra na fonte).
create or replace function bloqueia_auto_aprovacao()
returns trigger language plpgsql security definer as $$
begin
  if new.status in ('aprovado','rejeitado')
     and new.aprovado_por_id is not null
     and new.aprovado_por_id = new.solicitado_por_id then
    raise exception 'Quem solicitou o ajuste não pode aprová-lo ou rejeitá-lo.';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_bloqueia_auto_aprovacao on ajustes_caixa;
create trigger trg_bloqueia_auto_aprovacao
  before update on ajustes_caixa
  for each row execute function bloqueia_auto_aprovacao();
