-- ═══════════════════════════════════════════════════════════════
-- Studio Favola — Esquema do banco (Supabase / PostgreSQL)
--
-- ATENÇÃO: as definições de tabela abaixo foram INFERIDAS a partir
-- do código do app (index.html) — os tipos e constraints reais podem
-- diferir. Elas servem como documentação e para recriar o banco do
-- zero. NÃO execute os CREATE TABLE em um banco que já tem dados.
--
-- MIGRAÇÕES: ver docs/migracao-2026-08.sql — arquivo único e idempotente
-- com diagnóstico, allowlist RLS, trigger de dupla aprovação, backfill
-- do a_receber legado e a RPC aprovar_ajuste. É a fonte da verdade das
-- políticas/triggers vigentes.
-- ═══════════════════════════════════════════════════════════════

-- ── usuarios ─────────────────────────────────────────────────────
-- Espelha auth.users; guarda o nome de exibição da sócia.
create table if not exists usuarios (
  id   uuid primary key references auth.users(id),
  nome text
);

-- ── contratos (página Projetos) ──────────────────────────────────
create table if not exists contratos (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz default now(),
  numero           integer,
  nome_contrato    text,
  cliente          text,
  contato          text,
  tipologia        text,        -- Interiores | Arquitetônico | Comercial | Arq + Int
  servico          text,        -- Projeto | Consultoria | Detalhamento | Acompanhamento
  valor_contrato   numeric,
  parcelas         integer default 1,
  -- LEGADA/MORTA: o app calcula o "a receber" somando as entradas pendentes
  -- (contratoAReceber em js/data.js). Saldos antigos viraram entradas
  -- '[Backfill saldo legado]' (migracao-2026-08.sql, Seção 4). Não gravar.
  a_receber        numeric default 0,
  conta            text,        -- 'pessoal' (PF) | 'jurídica' (PJ)
  status           text,        -- Ativo | Proposta | Pausado | Finalizado | Descontinuado
  data_inicio      date,
  data_fim         date,
  cidade           text,
  uf               text,
  origem           text,        -- Indicação | Family & friends | Contato comercial
  metros_quadrados text,
  obs              text
);

-- ── entradas (Financeiro) ────────────────────────────────────────
create table if not exists entradas (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz default now(),
  contrato_id    bigint references contratos(id),
  nome_contrato  text,
  cliente        text,
  tipo_entrada   text,          -- 'projeto' | 'rt' | 'ajuste de caixa'
  valor          numeric,
  data_pagamento date,
  conta          text,          -- 'pessoal' | 'jurídica'
  forma_pagto    text,          -- PIX | TED | Boleto | Cartão | Ajuste
  status         text,          -- Pago | A Receber | Atrasado
  -- DÍVIDA CONHECIDA: mes_ano é texto em formato legado 'DD/MM/YYYY'
  -- (sempre dia 01). O app normaliza vários formatos em normalizaMesAno().
  -- Não migrar sem plano — há dados de produção em formatos mistos.
  mes_ano        text,
  obs            text
);

-- ── saidas (Financeiro / Sócias) ─────────────────────────────────
create table if not exists saidas (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz default now(),
  contrato_id    bigint references contratos(id),
  nome_contrato  text,
  tipo_saida     text,          -- retirada de lucros | pró-labore | projeto despesa |
                                -- escritório despesa | marketing | honorários | imposto |
                                -- ajuste de caixa | outro
  descricao      text,
  valor          numeric,
  data_pagamento date,
  conta          text,
  socia          text,          -- Fernanda | Laís | Ambas | null
  status         text,          -- Pago | A Pagar | Atrasado
  mes_ano        text,          -- mesmo formato legado de entradas.mes_ano
  obs            text
);

-- ── rt_comissoes (página RT / Comissões) ─────────────────────────
create table if not exists rt_comissoes (
  id                 bigint generated by default as identity primary key,
  created_at         timestamptz default now(),
  projeto            text,      -- nome_contrato do contrato relacionado
  categoria          text,      -- Marcenaria, Pedras, Iluminação, ...
  fornecedor         text,
  contato_fornecedor text,
  valor_venda        numeric,
  percentual_rt      numeric,   -- fração (0.10 = 10%)
  valor_rt           numeric,
  a_receber          numeric default 0,
  data_fechamento    date,
  conta              text,
  status             text       -- A receber | Pago | Inadimplência
);

-- ── fluxo_caixa (NÃO USADA pelo app — o fluxo é calculado no cliente;
--    a query foi removida em ago/2026. A tabela permanece no banco.) ──
create table if not exists fluxo_caixa (
  id      bigint generated by default as identity primary key,
  mes_ano text
  -- demais colunas não utilizadas pelo app atual
);

-- ── contas_bancarias (aba Contas do Financeiro) ──────────────────
create table if not exists contas_bancarias (
  id            bigint generated by default as identity primary key,
  nome          text,           -- Ex: Nubank PJ, C6 PF
  tipo          text,           -- Conta Corrente PJ | Conta Corrente PF | Poupança | Carteira | Outro
  saldo_atual   numeric default 0,
  atualizado_em date,
  obs           text
);

-- ── ajustes_caixa (conciliação com dupla aprovação) ──────────────
create table if not exists ajustes_caixa (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz default now(),
  updated_at        timestamptz,
  valor_novo        numeric,
  valor_anterior    numeric,
  diferenca         numeric,
  motivo            text,
  data_referencia   date,
  solicitado_por    text,       -- nome de exibição (legado)
  aprovado_por      text,       -- nome de exibição (legado)
  solicitado_por_id uuid,       -- auth.users.id — ver migração abaixo
  aprovado_por_id   uuid,       -- auth.users.id — ver migração abaixo
  status            text        -- pendente | aprovado | rejeitado
);

-- ═══════════════════════════════════════════════════════════════
-- RLS — Row Level Security
--
-- RLS ativo em todas as tabelas. Além da política permissiva original
-- ("authenticated full access ... using (true)"), a migração 2026-08
-- adicionou uma política RESTRICTIVE por tabela: o usuário precisa
-- estar em `usuarios` (allowlist via is_socia()). Signup público deve
-- permanecer DESABILITADO no painel do Supabase.
--
-- Políticas, triggers (protege_ajuste_caixa) e a RPC aprovar_ajuste
-- vigentes estão em docs/migracao-2026-08.sql — não duplicar aqui.
-- ═══════════════════════════════════════════════════════════════
